version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: deployments/backend.Dockerfile
    env_file:
      - ./backend/.env.docker
    environment:
      DATABASE_URL: sqlite+aiosqlite:///./data/accessvault.db
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: deployments/frontend.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

